version: 1
services:
  - type: web
    name: drawboard-http-backend
    runtime: image
    image:
      name: docker.io/justvoid1/drawboard-http-backend:latest
    plan: free
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
      - key: JWT_SECRET

  - type: web
    name: drawboard-ws-backend
    runtime: image
    image:
      name: docker.io/justvoid1/drawboard-ws-backend:latest
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
      - key: JWT_SECRET

  - type: web
    name: drawboard-fe
    runtime: image
    image:
      name: docker.io/justvoid1/drawboard-fe:latest
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
      - key: SERVER_HTTP_URL
        value: http://drawboard-http-backend:4000
      - key: WS_URL
        value: ws://drawboard-ws-backend:8080
