name: Deploy the frontend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: |
            justvoid1/drawboard-fe:${{ github.sha }}
            justvoid1/drawboard-fe:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DIRECT_URL=${{ secrets.DIRECT_URL }}
            SERVER_HTTP_URL=${{ vars.SERVER_HTTP_URL }}
            SERVER_WS_URL=${{ vars.SERVER_WS_URL }}
            NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_WS_URL=${{ vars.NEXT_PUBLIC_WS_URL }}
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_FE_DEPLOY_HOOK }}"
